name: Documentation
description: Suggest improvements or report issues with documentation
labels: ["documentation"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What documentation needs to be added, updated, or fixed?
    validations:
      required: true
  - type: textarea
    id: current-state
    attributes:
      label: Current State
      description: What is currently missing or incorrect?
    validations:
      required: false
  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
    validations:
      required: false
